name: "Tracearr"
description: "Real-time monitoring for Plex, Jellyfin, and Emby."
version: "1.4.27.2"
slug: "tracearr"
url: "https://github.com/connorgallopo/Tracearr"
arch:
  - aarch64
  - amd64
ports:
  3000/tcp: 3000
map:
  - data:rw
  - media:rw
  - share:rw
options: {}
schema: {}
icon: "icon.png"
logo: "logo.png"
