name: "Wizarr"
version: "2026.9.0"
slug: "wizarr_custom"
description: "Wizarr instance running as a Home Assistant add-on"
url: "https://github.com/wizarrrr/wizarr"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
ports:
  5690/tcp: 5690
ports_description:
  5690/tcp: "Wizarr Web Interface"
options: {}
schema: {}
icon: "icon.png"
logo: "logo.png"
